##
## Makefile for MiniLibX in /home/boulon/work/c/raytraceur/minilibx
## 
## Made by Olivier Crouzet
## Login   <ol@epitech.net>
## 
## Started on  Tue Oct  5 15:56:43 2004 Olivier Crouzet
## Last update Tue May 15 15:44:41 2007 Olivier Crouzet
##

## Please use configure script

MAGENTA = \033[36m
COLOR_RESET = \033[0m

all	: do_configure

do_configure	:
	@./configure
	@echo "$(MAGENTA) Libx compiled successfully 👾 $(COLOR_RESET)"

clean	:
	./configure clean

fclean	:
	./configure clean

re	: clean all
